run:
  tests: true
  skip-dirs:
    - _fold
    - lib

output:
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    #    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
#    - stylecheck
#    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  errcheck:
    ignore: fmt:.*,Read|Write|Close|Exec,io:Copy
  exhaustive:
    default-signifies-exhaustive: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec